"""add_recovery_pin_to_user

Revision ID: 4fb729d7ad6c
Revises: 21ba59b5aece
Create Date: 2026-07-10 10:00:11.408405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb729d7ad6c'
down_revision = '21ba59b5aece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recovery_pin', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('recovery_pin')

    # ### end Alembic commands ###
