"""extend report_history with premium fields

Revision ID: 648fa1a1ebb7
Revises: f102937d1415
Create Date: 2026-07-09 14:11:07.460052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648fa1a1ebb7'
down_revision = 'f102937d1415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('share_key', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_downloaded', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['share_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('last_downloaded')
        batch_op.drop_column('share_key')
        batch_op.drop_column('is_favorite')
        batch_op.drop_column('version')
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_path')
        batch_op.drop_column('report_name')

    # ### end Alembic commands ###
