"""Add expected salary growth expected inflation and prediction history table

Revision ID: 70266140d951
Revises: dda77f787501
Create Date: 2026-07-08 12:49:12.861672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70266140d951'
down_revision = 'dda77f787501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('salary_growth', sa.Float(), nullable=False),
    sa.Column('inflation_rate', sa.Float(), nullable=False),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('projected_con', sa.Float(), nullable=False),
    sa.Column('projected_mod', sa.Float(), nullable=False),
    sa.Column('projected_agg', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_salary_growth', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('expected_inflation', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('expected_inflation')
        batch_op.drop_column('expected_salary_growth')

    op.drop_table('prediction_history')
    # ### end Alembic commands ###
