"""add financial health tables

Revision ID: b56ab59f9b00
Revises: 066a7b73cc8d
Create Date: 2026-07-09 10:43:51.317027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56ab59f9b00'
down_revision = '066a7b73cc8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('savings_rate', sa.Float(), nullable=False),
    sa.Column('investment_ratio', sa.Float(), nullable=False),
    sa.Column('expense_ratio', sa.Float(), nullable=False),
    sa.Column('budget_score', sa.Float(), nullable=False),
    sa.Column('emergency_fund_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_health', schema=None) as batch_op:
        batch_op.create_index('idx_financial_health_user', ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_income', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('monthly_income')

    with op.batch_alter_table('financial_health', schema=None) as batch_op:
        batch_op.drop_index('idx_financial_health_user')

    op.drop_table('financial_health')
    # ### end Alembic commands ###
