"""Add financial health fields and table

Revision ID: dda77f787501
Revises: 066a7b73cc8d
Create Date: 2026-07-08 12:23:37.182618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda77f787501'
down_revision = '066a7b73cc8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_health_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('savings_rate', sa.Float(), nullable=False),
    sa.Column('investment_ratio', sa.Float(), nullable=False),
    sa.Column('expense_ratio', sa.Float(), nullable=False),
    sa.Column('budget_score', sa.Float(), nullable=False),
    sa.Column('emergency_fund_score', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_income', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('emergency_savings', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('emergency_savings')
        batch_op.drop_column('monthly_income')

    op.drop_table('financial_health_history')
    # ### end Alembic commands ###
