"""add report history table

Revision ID: f102937d1415
Revises: 75c42997bc92
Create Date: 2026-07-09 11:35:53.801704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f102937d1415'
down_revision = '75c42997bc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=250), nullable=False),
    sa.Column('generated_date', sa.DateTime(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_history', schema=None) as batch_op:
        batch_op.create_index('idx_report_history_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_history', schema=None) as batch_op:
        batch_op.drop_index('idx_report_history_user')

    op.drop_table('report_history')
    # ### end Alembic commands ###
